# Generated by Django 5.2.9 on 2025-12-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Dinheiro'), ('debit', 'Cartão de Débito'), ('credit', 'Cartão de Crédito'), ('pix', 'PIX')], max_length=20, verbose_name='Tipo de pagamento')),
                ('name', models.CharField(blank=True, help_text='Ex: Cartão Nubank, Dinheiro Vivo', max_length=100, verbose_name='Nome/Descrição')),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor disponível')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
