# Generated by Django 5.2.9 on 2025-12-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('debit', 'Cartão de Débito'), ('credit', 'Cartão de Crédito'), ('pix', 'PIX'), ('ticket', 'Ticket Alimentação'), ('paypal', 'PayPal')], max_length=20, verbose_name='Tipo de pagamento'),
        ),
    ]
