# Generated by Django 5.2.9 on 2025-12-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de barras')),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Último preço')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Imagem')),
                ('times_purchased', models.IntegerField(default=0, verbose_name='Vezes comprado')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-times_purchased', '-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('store_name', models.CharField(blank=True, max_length=100, verbose_name='Loja')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preços',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
