# Generated by Django 5.2.9 on 2025-12-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da lista')),
                ('planned_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Orçamento planejado')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total gasto')),
                ('status', models.CharField(choices=[('active', 'Em Andamento'), ('completed', 'Finalizada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('payment_methods', models.ManyToManyField(blank=True, related_name='shopping_lists', to='payments.paymentmethod', verbose_name='Formas de pagamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lista de Compras',
                'verbose_name_plural': 'Listas de Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Imagem')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('is_checked', models.BooleanField(default=False, help_text='Indica se o item foi colocado no carrinho', verbose_name='Marcado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist', verbose_name='Lista de compras')),
            ],
            options={
                'verbose_name': 'Item da Lista',
                'verbose_name_plural': 'Itens da Lista',
                'ordering': ['-created_at'],
            },
        ),
    ]
