# Generated by Django 5.2.9 on 2025-12-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Nota Fiscal (PDF)'),
        ),
    ]
